# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /share/apps/cmake/3.12.4/bin/cmake

# The command to remove a file.
RM = /share/apps/cmake/3.12.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /jlf/acmccormack1/SIDR3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /jlf/acmccormack1/SIDR3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/share/apps/cmake/3.12.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/share/apps/cmake/3.12.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/share/apps/cmake/3.12.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/share/apps/cmake/3.12.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/share/apps/cmake/3.12.4/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/share/apps/cmake/3.12.4/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/share/apps/cmake/3.12.4/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /jlf/acmccormack1/SIDR3/CMakeFiles /jlf/acmccormack1/SIDR3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /jlf/acmccormack1/SIDR3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SIDR2.0

# Build rule for target.
SIDR2.0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SIDR2.0
.PHONY : SIDR2.0

# fast build rule for target.
SIDR2.0/fast:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/build
.PHONY : SIDR2.0/fast

src/kmer_hash.o: src/kmer_hash.c.o

.PHONY : src/kmer_hash.o

# target to build an object file
src/kmer_hash.c.o:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/kmer_hash.c.o
.PHONY : src/kmer_hash.c.o

src/kmer_hash.i: src/kmer_hash.c.i

.PHONY : src/kmer_hash.i

# target to preprocess a source file
src/kmer_hash.c.i:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/kmer_hash.c.i
.PHONY : src/kmer_hash.c.i

src/kmer_hash.s: src/kmer_hash.c.s

.PHONY : src/kmer_hash.s

# target to generate assembly for a file
src/kmer_hash.c.s:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/kmer_hash.c.s
.PHONY : src/kmer_hash.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/main.c.s
.PHONY : src/main.c.s

src/param.o: src/param.c.o

.PHONY : src/param.o

# target to build an object file
src/param.c.o:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/param.c.o
.PHONY : src/param.c.o

src/param.i: src/param.c.i

.PHONY : src/param.i

# target to preprocess a source file
src/param.c.i:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/param.c.i
.PHONY : src/param.c.i

src/param.s: src/param.c.s

.PHONY : src/param.s

# target to generate assembly for a file
src/param.c.s:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/param.c.s
.PHONY : src/param.c.s

src/pipeline.o: src/pipeline.c.o

.PHONY : src/pipeline.o

# target to build an object file
src/pipeline.c.o:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/pipeline.c.o
.PHONY : src/pipeline.c.o

src/pipeline.i: src/pipeline.c.i

.PHONY : src/pipeline.i

# target to preprocess a source file
src/pipeline.c.i:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/pipeline.c.i
.PHONY : src/pipeline.c.i

src/pipeline.s: src/pipeline.c.s

.PHONY : src/pipeline.s

# target to generate assembly for a file
src/pipeline.c.s:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/pipeline.c.s
.PHONY : src/pipeline.c.s

src/pylink.o: src/pylink.c.o

.PHONY : src/pylink.o

# target to build an object file
src/pylink.c.o:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/pylink.c.o
.PHONY : src/pylink.c.o

src/pylink.i: src/pylink.c.i

.PHONY : src/pylink.i

# target to preprocess a source file
src/pylink.c.i:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/pylink.c.i
.PHONY : src/pylink.c.i

src/pylink.s: src/pylink.c.s

.PHONY : src/pylink.s

# target to generate assembly for a file
src/pylink.c.s:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/pylink.c.s
.PHONY : src/pylink.c.s

src/sequence.o: src/sequence.c.o

.PHONY : src/sequence.o

# target to build an object file
src/sequence.c.o:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/sequence.c.o
.PHONY : src/sequence.c.o

src/sequence.i: src/sequence.c.i

.PHONY : src/sequence.i

# target to preprocess a source file
src/sequence.c.i:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/sequence.c.i
.PHONY : src/sequence.c.i

src/sequence.s: src/sequence.c.s

.PHONY : src/sequence.s

# target to generate assembly for a file
src/sequence.c.s:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/sequence.c.s
.PHONY : src/sequence.c.s

src/sequencing_data.o: src/sequencing_data.c.o

.PHONY : src/sequencing_data.o

# target to build an object file
src/sequencing_data.c.o:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/sequencing_data.c.o
.PHONY : src/sequencing_data.c.o

src/sequencing_data.i: src/sequencing_data.c.i

.PHONY : src/sequencing_data.i

# target to preprocess a source file
src/sequencing_data.c.i:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/sequencing_data.c.i
.PHONY : src/sequencing_data.c.i

src/sequencing_data.s: src/sequencing_data.c.s

.PHONY : src/sequencing_data.s

# target to generate assembly for a file
src/sequencing_data.c.s:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/sequencing_data.c.s
.PHONY : src/sequencing_data.c.s

src/taxonomy.o: src/taxonomy.c.o

.PHONY : src/taxonomy.o

# target to build an object file
src/taxonomy.c.o:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/taxonomy.c.o
.PHONY : src/taxonomy.c.o

src/taxonomy.i: src/taxonomy.c.i

.PHONY : src/taxonomy.i

# target to preprocess a source file
src/taxonomy.c.i:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/taxonomy.c.i
.PHONY : src/taxonomy.c.i

src/taxonomy.s: src/taxonomy.c.s

.PHONY : src/taxonomy.s

# target to generate assembly for a file
src/taxonomy.c.s:
	$(MAKE) -f CMakeFiles/SIDR2.0.dir/build.make CMakeFiles/SIDR2.0.dir/src/taxonomy.c.s
.PHONY : src/taxonomy.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... SIDR2.0"
	@echo "... src/kmer_hash.o"
	@echo "... src/kmer_hash.i"
	@echo "... src/kmer_hash.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/param.o"
	@echo "... src/param.i"
	@echo "... src/param.s"
	@echo "... src/pipeline.o"
	@echo "... src/pipeline.i"
	@echo "... src/pipeline.s"
	@echo "... src/pylink.o"
	@echo "... src/pylink.i"
	@echo "... src/pylink.s"
	@echo "... src/sequence.o"
	@echo "... src/sequence.i"
	@echo "... src/sequence.s"
	@echo "... src/sequencing_data.o"
	@echo "... src/sequencing_data.i"
	@echo "... src/sequencing_data.s"
	@echo "... src/taxonomy.o"
	@echo "... src/taxonomy.i"
	@echo "... src/taxonomy.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

